spring.application.name=SmartHire_AI
spring.datasource.url=jdbc:mysql://localhost:3306/SmartHire_AI
spring.datasource.username=root
spring.datasource.password=gitesh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
loging.level.root=DEBUG
loging.level.com.sgt.ExpenseTracker=INFO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chiragkrishnani13@gmail.com
spring.mail.password=ogbc sska chvd xvwn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

